name: CI/CD Rust

on:
  push:
    branches:
      - qa
      - hml
      - main

jobs:
  setup_dependencies:
    name: Instalar Dependências de Sistema
    runs-on: [self-hosted, Linux]

    steps:
      - name: Atualizar e instalar dependências básicas
        run: sudo apt-get update && sudo apt-get install -y build-essential docker.io

      - name: Iniciar serviço Docker
        run: |
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Verificar Docker
        run: docker --version

  build:
    name: Build Rust Project
    runs-on: [self-hosted, Linux]
    needs: setup_dependencies

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cargo Build
        run: cargo build --release

  test:
    name: Test Rust
    runs-on: [self-hosted, Linux]
    needs: build

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run Test
        run: cargo test --all --release

  docker_build:
    name: Build Docker Image
    runs-on: [self-hosted, Linux]
    needs: test

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t rust-app-local:latest .

  deploy_qa:
    name: Deploy to QA
    runs-on: [self-hosted, qa-machine]
    needs: docker_build
    if: github.ref == 'refs/heads/qa'

    steps:
      - name: Parar e remover container antigo em QA
        run: |
          docker stop rust-app || true
          docker rm rust-app || true

      - name: Rodar novo container em QA
        run: docker run -d -p 8080:8080 --name rust-app rust-app-local:latest

  deploy_hml:
    name: Deploy to HML
    runs-on: [self-hosted, hml-machine]
    needs: docker_build
    if: github.ref == 'refs/heads/hml'

    steps:
      - name: Parar e remover container antigo em HML
        run: |
          docker stop rust-app || true
          docker rm rust-app || true

      - name: Rodar novo container em HML
        run: docker run -d -p 8080:8080 --name rust-app rust-app-local:latest

  deploy_prod:
    name: Deploy to Production
    runs-on: [self-hosted, prod-machine]
    needs: docker_build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Parar e remover container antigo em Produção
        run: |
          docker stop rust-app || true
          docker rm rust-app || true

      - name: Rodar novo container em Produção
        run: docker run -d -p 8080:8080 --name rust-app rust-app-local:latest
