name: CI/CD Rust Local (Self-Hosted)

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Rust Project
    runs-on: [self-hosted, Linux]

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cargo Build
        run: cargo build --release

  test:
    name: Test Rust
    runs-on: [self-hosted, Linux]
    needs: build

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cargo Test
        run: cargo test --all --release

  docker_build:
    name: Build Docker Image
    runs-on: [self-hosted, Linux]
    needs: test

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t rust-app-local:latest .

  deploy:
    name: Deploy Container Locally
    runs-on: [self-hosted, Linux]
    needs: docker_build

    steps:
      - name: Parar e remover container antigo
        run: |
          docker stop rust-app || true
          docker rm rust-app || true

      - name: Rodar novo container
        run: docker run -d -p 8080:8080 --name rust-app rust-app-local:latest
